import Head from "next/head";
import styled from "styled-components";
import Sidebar from "../components/Sidebar";

export default function Home() {
    return (
        <Container>
            <Head>
                <title>LinkUP</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Sidebar />
        </Container>
    );
}

const Container = styled.div`
    background-color: #343a40;
`;
